### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by 8-V** [secondme2/secondme2.github.io#1]
Не работает)

**Comment by secondme2** [comment]
О, привет Димон

**Comment by secondme2** [comment]
Как в Рим съездил? Раньше кстати работало, с двух вф(привет соседям))))

**Comment by secondme2** [comment]
Я сейчас редко за компом сижу, пиши лучше в телеге, на телефоне в вайбер почти не захожу(зрение упало, жесть =((

**Comment by 8-V** [comment]
ТАМ_ТАМ_ДАМММММММ
